version: '2'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: lthub/moodle
    build: .
    ports:
      - 8080:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    # uncomment the 'volumes' section to enable a shared volume with docker-compose
    volumes:
      - ./.data/web:/moodledata:rw
      # do not uncomment this when starting a new instance from scratch as
      # init script won't be able to move this file
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DB_HOST=db
      - MOODLE_DB_PORT=
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodle
      - MOODLE_DB_PASSWORD=password
      - MOODLE_DB_PREFIX=
      - MOODLE_URL=http://localhost:8080
#  memcached:
#    image: memcached:1.5-alpine
